export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  CANDIDATES: '/candidates',
  JOBS: '/jobs',
  APPLICATIONS: '/applications',
  AGENTS: '/agents',
  CALLS: '/calls',
  COMPANIES: '/companies',
  EMAILS: '/emails',
  REENGAGEMENT: '/reengagement',
  ANALYTICS: '/analytics',
  ACTIVITY: '/activity',
  SETTINGS: '/settings',
} as const;
