-- Migration 017: lock down the resumes storage bucket
--
-- The original policies (001) gated only on auth.role() = 'authenticated' with
-- no org scoping — ANY logged-in user could read or overwrite EVERY org's
-- resumes. No client-side code touches storage: all uploads/reads go through
-- the backend with the service role (which bypasses these policies), so the
-- bucket needs no authenticated-user policies at all. Signed URLs generated by
-- the backend keep working.

UPDATE storage.buckets SET public = false WHERE id = 'resumes';

DROP POLICY IF EXISTS resume_upload ON storage.objects;
DROP POLICY IF EXISTS resume_read ON storage.objects;

-- No replacement policies on purpose: resume access is backend-mediated and
-- org-scoped there. If direct client access is ever needed, add policies that
-- check the object path's org prefix against get_user_org_id().
